agents:
  gitlab:
    name: "GitLab Assistant"
    description: "Handles GitLab project queries"
    host: "127.0.0.1"
    port: 2024
  Pishool:
    name: "Pishool"
    description: "Handles Opensearch queriesticket queries"
    host: "https://logagent-part2.partdp.ai
    port: 443
