"""Format the final response returned by the graph."""

from __future__ import annotations

import logging
from typing import Dict

from ..types import AgentState

logger = logging.getLogger(__name__)


async def format_response(state: AgentState) -> Dict[str, str]:
    """Format the response payload emitted by the workflow."""
    logger.info("Formatting final response.")

    response = state.get("response")
    if response is None:
        logger.error("`response` not found in state. Cannot format final output.")
        return {"response": "Error: No response was generated by the agent."}

    return {"response": response}

